name: geologger
description: Add geo locations to the Traefic access log.
version: 1.5.1
repository: https://github.com/fischerscode/Traefik-GeoLogger
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  geologger:

dependencies:
  args: ^2.3.0
  dart_geohash: ^2.0.1
  maxminddb: ^1.2.0
  extendedip: ^1.0.0
  version: ^3.0.2
  prometheus_client: ^1.0.0
  dcli: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
  yaml: ^3.1.0
  yamltools: ^1.1.1
