name: geologger
description: Add geo locations to the Traefic access log.
version: 1.4.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_geohash: ^2.0.1
  maxminddb: ">=1.1.0 <2.0.0"
  extendedip: ">=1.0.0 <2.0.0"
  version: ^2.0.0
  prometheus_client: ^0.5.0
  dcli: ^1.14.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.12
  yaml: ^3.1.0
  yamltools: ^1.1.1
