name: geologger
description: Add geo locations to the Traefic access log.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  maxminddb: ^1.0.0
  version: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.12
  yaml: ^3.1.0
  yamltools: ^1.1.1
