name: Build Docker with Database

on:
  release:
    types:
      - published
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download City database
        id: download
        run: |
          wget -O GeoLite2-City.tar.gz https://download.maxmind.com/app/geoip_download\?edition_id\=GeoLite2-City\&license_key\=${{ secrets.MAXMIND_KEY }}\&suffix\=tar.gz
          tar -xf GeoLite2-City.tar.gz
          rm GeoLite2-City.tar.gz
          mv $(ls -d -- GeoLite2-City_[0-9]*)/GeoLite2-City.mmdb ./
          echo "::set-output name=build::$(ls -d -- GeoLite2-City_[0-9]* | sed -e 's/GeoLite2-City_//g')"
          rm -r GeoLite2-City_*
          pwd
          ls -l

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fischerscode/traefik-geologger-city
          tags: |
            type=semver,prefix=v,pattern={{version}}
            type=semver,prefix=v,pattern={{version}},suffix=_${{ steps.download.outputs.build }}
            type=semver,prefix=v,pattern={{version}},suffix=${{ steps.download.outputs.build }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.database
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
