name: Build Docker with Database Daily

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          owner: fischerscode
          repo: Traefik-GeoLogger
          excludes: prerelease, draft

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.release }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download City database
        id: download
        run: |
          wget -O GeoLite2-City.tar.gz https://download.maxmind.com/app/geoip_download\?edition_id\=GeoLite2-City\&license_key\=${{ secrets.MAXMIND_KEY }}\&suffix\=tar.gz
          tar -xf GeoLite2-City.tar.gz
          rm GeoLite2-City.tar.gz
          mv $(ls -d -- GeoLite2-City_[0-9]*)/GeoLite2-City.mmdb ./
          echo "::set-output name=build::$(ls -d -- GeoLite2-City_[0-9]* | sed -e 's/GeoLite2-City_//g')"
          rm -r GeoLite2-City_*
          pwd
          ls -l

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fischerscode/traefik-geologger-city
          tags: |
            type=raw,value=${{ steps.release.outputs.release }}
            type=raw,value=${{ steps.release.outputs.release }}_${{ steps.download.outputs.build }}
            type=raw,value=${{ steps.release.outputs.release }}${{ steps.download.outputs.build }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.database
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
