name: Release

on:
  release:
    types:
      - "created"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: geologger.linux
          - os: macOS-latest
            output-name: geologger.mac
          - os: windows-latest
            output-name: geologger.windows.exe

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
      - run: mkdir build
      - name: build
        run: dart2native bin/geologger.dart -v -o build/${{ matrix.output-name }}
      - name: upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.output-name }}
          asset_name: ${{ matrix.output-name }}
          tag: ${{ github.ref }}
          overwrite: true

  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fischerscode/tagger@v0.1
        with:
          prefix: v
